### ISSUE TITLE
undefined is not an object (evaluating '_appList.APP_LIST[key].pkgName')

### ISSUE THREAD

**Issue by kriptonhaz** [redpandatronicsuk/react-native-check-app-install#11]
Hi, I tried just like the readme and just like the title said,

my environment so far:
RN: 0.48.4
react-native-check-app-install 0.0.4

thanks

**Comment by boozi2** [comment]
Did anyone mange to solve this issue?

**Comment by gabrielbuzziv** [comment]
Got the same error, someone solved?

**Comment by MichaelQ1an** [comment]
I encountered the same problem. Turns out this npm package only checks a list of popular apps. You can find a file named `app-list.js` inside this package. When you try to detect an app that is not on the list, you will get this error.

**Comment by onitzschke** [comment]
fixed with https://github.com/redpandatronicsuk/react-native-check-app-install/pull/19

**Comment by brainman07** [comment]
Hi,
AppInstalledChecker.isAppInstalledAndroid('com.waze') still throws this error for me.
I'm running my app on OxygenOS version 9.0.6
Can you add Waze in app-list.js please? Apps outside this list still cannot be checked.

**Comment by wuodland** [comment]
Yes @brainman07 is right. The old line is still present inside node_modules. Please updated the npm model to have latest version.
cc @onitzschke @redpandatronicsuk

**Comment by irfanismaya20** [comment]
evaluating '_appList.APP_LIST[key].pkgName
